- continue-on-error 구문 추가

diff --git a/.github/workflows/devops.yml b/.github/workflows/devops.yml
--- a/.github/workflows/devops.yml
+++ b/.github/workflows/devops.yml
@@ -75,11 +75,15 @@ jobs:
       - name: Run tests
         # 이 단계의 ID입니다. 후속 단계에서 참조할 수 있습니다.
         id: run_tests
+        # 이 단계에서 오류가 발생해도 워크플로우를 계속 진행하도록 합니다. 하지만, 단계 자체는 실패 상태를 유지합니다.
+        continue-on-error: true
+        run: |
+          pytest test_1.py > pytest_output.txt 2>&1
         # 테스트를 실행한 후, 오류가 발생해도 exit 코드를 0으로 설정하여 워크플로우가 중단되지 않도록 합니다.
         # 이렇게 하면 후속 단계에서 테스트 결과를 확인할 수 있습니다.
         # true 는 exit 0 과 같은 역할을 한다.
-        run: |
-          pytest test_1.py > pytest_output.txt 2>&1 || true  # 오류가 발생해도 계속 실행하고 출력을 파일로 리디렉션합니다.
+#        run: |
+#          pytest test_1.py > pytest_output.txt 2>&1 || true  # 오류가 발생해도 계속 실행하고 출력을 파일로 리디렉션합니다.
 #        run: pytest test_1.py || true
 #        run: pytest test_1.py || exit 0
         # pytest는 기본적으로 test_*.py 또는 *_test.py 형식의 파일을 찾고, test_로 시작하는 함수들을 테스트로 인식합니다.
@@ -91,15 +95,15 @@ jobs:
       - name: Check test result - Success
         # 조건을 사용하여 이전 단계의 결과에 따라 Y 또는 N을 출력합니다.
         # conclusion 속성은 단계의 최종 상태(성공 또는 실패)를 나타냅니다.
-        if: ${{ steps.run_tests.conclusion == 'success' }}
-#        if: ${{ steps.run_tests.outcome == 'success' }}
+#        if: ${{ steps.run_tests.conclusion == 'success' }}
+        if: ${{ steps.run_tests.outcome == 'success' }}
         # 이전 단계가 성공했을 경우에만 이 단계를 실행합니다.
 #        if: success()
         run: echo Y
 
       - name: Check test result - Failure (Display error message)
-        if: ${{ steps.run_tests.conclusion == 'failure' }}
-#        if: ${{ steps.run_tests.outcome == 'failure' }}
+#        if: ${{ steps.run_tests.conclusion == 'failure' }}
+        if: ${{ steps.run_tests.outcome == 'failure' }}
         # 이전 단계가 실패했을 경우에만 이 단계를 실행합니다.
 #        if: failure()
         run: |
